apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: sample-flux-fail-chart
  namespace: flux-system
spec:
  interval: 1m0s
  url: https://github.com/yourrepohere/helm-charts.git
  ref:
    branch: your-branch-here
  secretRef:
    name: flux-system
